/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class waffleoRai_extractMyu_LzNative */

#ifndef _Included_waffleoRai_extractMyu_LzNative
#define _Included_waffleoRai_extractMyu_LzNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     waffleoRai_extractMyu_LzNative
 * Method:    lzCompressMatchC
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_waffleoRai_1extractMyu_LzNative_lzCompressMatchC
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     waffleoRai_extractMyu_LzNative
 * Method:    lzCompressMatchCForceLit
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_waffleoRai_1extractMyu_LzNative_lzCompressMatchCForceLit
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
