#ifndef SLPM87176_DATAARC_SYSTEM_H
#define SLPM87176_DATAARC_SYSTEM_H

typedef enum Arc_SystemFile {
	Sys_UI_Common = 0,
	Sys_TitleBanner,
	Sys_UI_Battlers,
	Sys_MenuBkg_GreenWhite,
	Sys_SolidColors,
	Sys_TitleBackground,
	Sys_BattleEff,
	Sys_MCIcon_Bell,
	Sys_StartLogo_Takara,
	Sys_UI_TitleMenu,
	Sys_DiscWarning,
	Sys_Test,
	Sys_MemoryIcons,
	Sys_MemoryPlaceholder,
	Sys_014, //Update when I figure out which menu this is from
	Sys_MenuBkg_TurqA,
	Sys_MenuBkg_TanA,
	Sys_LoadingBkg,
	Sys_SceneBkg_GlenA,
	Sys_MenuBkg_Yellow,
	Sys_UIIcon_MovieColl,
	Sys_MenuBkg_Pastel,
	Sys_MenuBkg_TealSpot,
	Sys_SceneImg_Sleepover,
	Sys_UI_FileSelect,
	Sys_StartLogo_Winkysoft,
	Sys_SceneBkg_BedroomNight,
	Sys_SceneImg_RingoYuki,
	Sys_UISprite_IchigoPush = 29,
	Sys_UI_AssignBeds,
	Sys_MCIcon_Masha,
	Sys_UI_OverworldMap,
	Sys_UI_AreaNames,
	Sys_MapBkg_Day,
	Sys_MapBkg_DayIceMnt,
	Sys_MapBkg_Night,
	Sys_MapBkg_NightIceMnt,
	Sys_MapBorder_Day,
	Sys_MapBorder_Night,
	Sys_UI_SoundTest = 48,
	Sys_MenuBkg_PinkBubble,
	Sys_UI_Memo,
	Sys_MenuBkg_Green,
	Sys_MenuBkg_PinkLace,
	Sys_UI_MewProfile,
	Sys_UI_KanaTabs,
	Sys_StartWarn_BrightRoom,
	Sys_UI_ItemExchange,
	Sys_UI_PicCostumes,
	Sys_MenuBkg_TanB,
	Sys_MenuBkg_TurqB,
	Sys_GameOver_Bkg,
	Sys_TitleLogo_GS2002,
	Sys_BattleBkg_PoisonSpringD1,
	Sys_ToyAd_WpnStawberry = 64,
	Sys_ToyAd_WpnMint,
	Sys_ToyAd_WpnLettuce,
	Sys_ToyAd_WpnPudding,
	Sys_ToyAd_WpnPomegranate,
	Sys_ToyAd_BerryRod,
	Sys_ToyAd_DressUpStrawberry,
	Sys_ToyAd_DressUpMint,
	Sys_ToyAd_DressUpLettuce,
	Sys_ToyAd_DressUpPudding,
	Sys_ToyAd_DressUpPomegranate,
	Sys_ToyAd_FigStrawberry,
	Sys_ToyAd_FigMint,
	Sys_ToyAd_FigLettuce,
	Sys_ToyAd_FigPudding,
	Sys_ToyAd_FigPomegranate,
	Sys_ToyAd_Minidoll,
	Sys_ToyAd_DrinkMachine,
	Sys_ToyAd_Teaset,
	Sys_AreaTag_Yuho,
	Sys_AreaTag_CtgMori,
	Sys_AreaTag_Shinjitsu,
	Sys_AreaTag_Yasuragi,
	Sys_AreaTag_Utakaze,
	Sys_AreaTag_IceMountain,
	Sys_AreaTag_SecretCave,
	Sys_AreaTag_Yamamichi,
	Sys_AreaTag_MysteryCave,
	Sys_AreaTag_RangerMori,
	Sys_AreaTag_Izumi,
	Sys_AreaTag_Uruwashi,
	Sys_AreaTag_Iyashi,
	Sys_AreaTag_RangerCottage,
	Sys_AreaTag_Cottage,
	Sys_BattleBkg_KitchenD,
	Sys_BattleBkg_PorchN,
	Sys_BattleBkg_ForestD,
	Sys_BattleBkg_ForestN,
	Sys_BattleBkg_SpringD,
	Sys_BattleBkg_FieldD,
	Sys_BattleBkg_IceCave,
	Sys_BattleBkg_Cave,
	Sys_BattleBkg_MeadowD,
	Sys_BattleBkg_MeadowN,
	Sys_BattleBkg_SpringN,
	Sys_BattleBkg_FieldN,
	Sys_BattleBkg_PoisonSpringD2,
} Arc_SystemFile;

#endif