#ifndef MYUC_UNKDATA6_H
#define MYUC_UNKDATA6_H

/*---------------------------------------
* Header file autogenerated by MyuCTemplatizer
* ---------------------------------------*/


#ifdef __cplusplus
extern "C" {
#endif

	extern uint8_t _udat6_dat_800fa754[];
	extern uint8_t _udat6_dat_800fa764[];
	extern uint8_t _udat6_dat_800fa774[];
	extern uint8_t _udat6_dat_800fa784[];
	extern uint8_t _udat6_dat_800fa794[];

#ifdef __cplusplus
}
#endif

#endif
