#ifndef MYUC_UNKDATA5_H
#define MYUC_UNKDATA5_H

/*---------------------------------------
* Header file autogenerated by MyuCTemplatizer
* ---------------------------------------*/


#ifdef __cplusplus
extern "C" {
#endif

	extern uint8_t _udat5_dat_800ed5b4[];
	extern uint32_t _udat5_dat_800f0100[];
	extern uint32_t _udat5_dat_800f9000[];

#ifdef __cplusplus
}
#endif

#endif
